import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getServerSession } from "next-auth/next"
import { authOptions } from './api/auth/[...nextauth]'

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps({ req, res }) {
  return {
    props: {
      session: await getServerSession(req, res, authOptions)
    }
  }
}

export async function getStaticProps() {
  // Fetch data from an API or database
  const res = await fetch('https://fakestoreapi.com/products/categories');
  const featuredProducts = await res.json();

  return {
    props: {
      featuredProducts,
    },
  };
}


export default function Home({ featuredProducts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>Featured Products</h1>
          <ul>
            {featuredProducts.map((product) => (
              <li>{product}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}